import os
import numpy as np
import time
import tempfile
from pathlib import Path
import shutil

cwd = os.getcwd()
cwd = cwd + '/'

instrument_label = 1

#instrument_label = input("instrument_label=?, enter 1 for OCI, 2 for MODIS, 3 for SeaWifs, 4 for MISR: ")

instrument_label=int(instrument_label)  # 1: OCI table 2: MODIS A 3: SeaWifs

if instrument_label < 1 or instrument_label >4 :
        sys.exit("Your instrument_label value is invalid")

if instrument_label == 1 :
        instrument_strbase='OCI'
elif instrument_label == 2 :
        instrument_strbase='MODISa'
elif instrument_label == 3 :
        instrument_strbase='SeaWifs'
elif instrument_label == 4 :
        instrument_strbase='Misr'

path= cwd + instrument_strbase + '/'

# Here I get the directory path for each aerosol models- 80 in total
mdl = np.arange(11,21, dtype=int)
rh = np.array(['0.300000', '0.500000', '0.700000', '0.750000', '0.800000', '0.850000','0.900000', '0.950000'])
fpath = []
for i in range(len(mdl)):
    for j in range(len(rh)):
        fpath.append('Inputfile_Dir_'+instrument_strbase+'AerosolModel'+str(mdl[i])+'rh_'+rh[j])
fpath = np.array(fpath)

outpath = instrument_strbase + '/rt_outputs'
if os.path.isdir(outpath):
    pass
else:
    os.mkdir(outpath)
# Read in the slurm array index
#idx=0
idx = int(os.environ["SLURM_ARRAY_TASK_ID"])

# choose number of cores and create array of indices
# there are 3312 input files generated by PWZ-permutations of inputs
ncores = 829
sarray = np.linspace(0, 3312, ncores, dtype=int)#277

# loop over the 80-aerosol model
for i in range(80):
    inpf = []
    # loop over the 3312 files for each model
    for x2 in os.listdir(path+fpath[i]):
        inpf.append(x2)
    inpf = np.array(inpf)
    inp=[]
    for j in range(len(inpf)):
        if inpf[j][:5] == 'input':
            inp.append(inpf[j])
    inp = np.array(inp)

    for k in range(sarray[idx],sarray[idx+1]):
        tmpdir = tempfile.TemporaryDirectory()
        os.chdir(tmpdir.name)
        #os.system('ls')
        command = cwd + 'rtsos_GSFC_AC_LUT.exe ' +  path+fpath[i]+'/'+inp[k]
        shutil.copy(cwd+'auxiliary_directory', tmpdir.name)
        shutil.copy(cwd+'gas_absorption_coeff_dir', tmpdir.name)
        shutil.copy(cwd+'OCI_MIE_DIR.txt', tmpdir.name)
        os.system(command)
        #os.system('ls')
        #print(command)
        ofile = 'output' + inp[k][5:] + '.h5'
        tmpoutputfile = Path(tmpdir.name + '/' + ofile)
        shutil.copy(tmpoutputfile, cwd + outpath)

