[project]
name = "zhai-rt"
version = "0.2.1"
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.23",
    "xarray>=2022.3",
    "netcdf4>=1.6.1",
    "h5netcdf @ git+https://git@github.com/itcarroll/h5netcdf@null_dimension_scale",
    "dask>=2022.10.2",
]

[project.optional-dependencies]
test = ["pytest"]

[project.scripts]
rt-AC-LUT = "zhai_rt.rt_AC_LUT:main"
rt-PACE = "zhai_rt.rt_PACE:main"
rt-PHMX = "zhai_rt.rt_PHMX:main"

[tool.scikit-build]
ninja.minimum-version = "1.10"
cmake.minimum-version = "3.17.2"

[build-system]
requires = [
    "scikit-build-core",
    "numpy>=1.23",
]
build-backend = "scikit_build_core.build"
