[project]
name = "zhai-rt"
version = "0.1.2"
requires-python = ">=3.10,<3.11"
dependencies = [
    "numpy>=1.23",
    "xarray>=2022.3",
    "netcdf4>=1.6.1",
    "h5netcdf @ git+https://git@github.com/itcarroll/h5netcdf@null_dimension_scale",
    "dask>=2022.10.2",
]

[project.scripts]
rt-AC-LUT = "zhai_rt.rt_AC_LUT:main"
rt-PACE = "zhai_rt.rt_PACE:main"

[tool.setuptools]
packages = ["zhai_rt"]
package-dir = { zhai_rt = "scripts" }

[build-system]
requires = [
    "setuptools>=65.0",
    "scikit-build",
]
build-backend = "setuptools.build_meta"
